In [6]:
import cv2
import numpy as np
import os

In [10]:
# /Users/kevinhui/WorkPlace/ThesisProject/MyExperiments/jpg_files/Example/CCL_Results
# ../jpg_files/Example/n=500d=6_38981.png

result_dir = "/Users/kevinhui/WorkPlace/ThesisProject/MyExperiments/jpg_files/Example/CCL_Results/"
source_path = "/Users/kevinhui/WorkPlace/ThesisProject/MyExperiments/jpg_files/Example/n=500d=6_38981.jpg"
grey_file = "n=500d=6_38981_grey.jpg"
binary_file = "n=500d=6_38981_binary.jpg"
result_file = "n=500d=6_38981_CCL.jpg"

# # Loading the image
# img = cv2.imread(source_path)
  
# # preprocess the image
# gray_img = cv2.cvtColor(img , cv2.COLOR_BGR2GRAY)
  
# # Applying 7x7 Gaussian Blur
# # blurred = cv2.GaussianBlur(gray_img, (7, 7), 0)
  
# # Applying threshold
# threshold = cv2.threshold(blurred, 0, 255,
#     cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1] 
  
# # Apply the Component analysis function
# analysis = cv2.connectedComponentsWithStats(threshold,
#                                             4,
#                                             cv2.CV_32S)
# (totalLabels, label_ids, values, centroid) = analysis
  
# # Initialize a new image to store 
# # all the output components
# output = np.zeros(gray_img.shape, dtype="uint8")
  
# # Loop through each component
# for i in range(1, totalLabels):
    
#       # Area of the component
#     area = values[i, cv2.CC_STAT_AREA] 
      
#     if (area > 140) and (area < 400):
#         componentMask = (label_ids == i).astype("uint8") * 255
#         output = cv2.bitwise_or(output, componentMask)
        
# cv2.imwrite(target_path, output)


In [26]:
# 读入图片
img = cv2.imread(source_path)
# 中值滤波，去噪
img = cv2.medianBlur(img, 3)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite(os.path.join(result_dir, grey_file), gray)

# 阈值分割得到二值化图片
ret, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
cv2.imwrite(os.path.join(result_dir, binary_file), binary)
# 膨胀操作
# kernel2 = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
# bin_clo = cv2.dilate(binary, kernel2, iterations=2)

# 连通域分析
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(binary, connectivity=4)
# num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(bin_clo, connectivity=8)

# 查看各个返回值
# 连通域数量
print('num_labels = ',num_labels)
# 连通域的信息：对应各个轮廓的x、y、width、height和面积
print('stats = ',stats)
# 连通域的中心点
print('centroids = ',centroids)
# 每一个像素的标签1、2、3.。。，同一个连通域的标签是一致的
print('labels = ',labels)

# 不同的连通域赋予不同的颜色
# output = np.zeros((img.shape[0], img.shape[1], 3), np.uint8)
# output[:, :] = [255, 255, 255] 
output = img
for i in range(1, num_labels):
    # Area of the component
    area = stats[i, cv2.CC_STAT_AREA] 
    if area > 10000:
        print(str(i) + " area is " + str(area))
        mask = labels == i
        output[:, :, 0][mask] = np.random.randint(0, 255)
        output[:, :, 1][mask] = np.random.randint(0, 255)
        output[:, :, 2][mask] = np.random.randint(0, 255)
#         componentMask = (label_ids == i).astype("uint8") * 255
#         output = cv2.bitwise_or(output, componentMask)
        
    
cv2.imwrite(os.path.join(result_dir, result_file), output)



num_labels =  752
stats =  [[      0       0    2000    2000 1618231]
 [      0       0      15      40     409]
 [     28       0       5       3      11]
 ...
 [    502    1990     109      10     726]
 [    890    1991     135       9     659]
 [   1033    1999       4       1       4]]
centroids =  [[9.91592105e+02 1.07944332e+03]
 [5.18581907e+00 1.76919315e+01]
 [2.97272727e+01 7.27272727e-01]
 ...
 [5.51005510e+02 1.99559642e+03]
 [9.51033384e+02 1.99650683e+03]
 [1.03450000e+03 1.99900000e+03]]
labels =  [[  1   1   1 ...   3   3   3]
 [  1   1   1 ...   3   3   3]
 [  1   1   1 ...   3   3   3]
 ...
 [398 398 398 ... 675 675 675]
 [398 398 398 ... 675 675 675]
 [398 398 398 ... 675 675 675]]
3 area is 596381
22 area is 14379
35 area is 22450
40 area is 20567
79 area is 11166
141 area is 53329
166 area is 106635
179 area is 18682
222 area is 23599
229 area is 12038
288 area is 20860
293 area is 12806
299 area is 13771
304 area is 89359
318 area is 30109
359 area is 10277
398 ar

True